# Generated by Django 4.2.25 on 2025-10-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('blocek_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tags', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('blocek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.receipt')),
            ],
        ),
    ]
