# Generated by Django 4.2.25 on 2025-11-06 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_remove_receipt_org_unit_receipt_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_name_english', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('receipt_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ai_name_without_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_name_english', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_quantity_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ai_quantity_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='core.product')),
            ],
            options={
                'db_table': 'receipt_items',
            },
        ),
        migrations.CreateModel(
            name='StoreUnit',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(default='Slovensko', max_length=50)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('building_number', models.CharField(blank=True, max_length=20, null=True)),
                ('property_registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'store_units',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='products_items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products_items',
            name='receipt',
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issue_date']},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='free_tax_amount',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_building_number',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_country',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_municipality',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_postal_code',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_street_name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='vat_rate_basic',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='vat_rate_reduced',
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Slovensko', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fs_receipt_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_sessions',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='receipts',
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Products_Items',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='storeunit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='core.organization'),
        ),
        migrations.AddField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.receipt'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='store_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.storeunit'),
        ),
    ]
