# Generated by Django 5.2.7 on 2025-11-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_receiptitem_storeunit_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='fs_receipt_id',
            field=models.CharField(default='TEMP_ID', max_length=100, unique=True),
        ),
    ]
